server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: rag-api
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB
    username: RAG_APP
    password: Rag123456
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

agent:
  planner:
    type: rule

answer:
  mode: rule
  langchain4j:
    enabled: false
    modelName: gpt-4o-mini
    timeoutMs: 8000
    maxTokens: 800
    fallbackEnabled: true
    apiKey: ${OPENAI_API_KEY:}
