CREATE TABLE RAG_ENTITIES (
    ID NUMBER PRIMARY KEY,
    ENTITY_NAME VARCHAR2(500),
    ENTITY_TYPE VARCHAR2(50),
    NORMALIZED_NAME VARCHAR2(255),
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE RAG_ENTITIES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE RAG_DOCUMENT_ENTITY_LINKS (
    ID NUMBER PRIMARY KEY,
    DOCUMENT_ID NUMBER NOT NULL,
    CHUNK_ID NUMBER,
    ENTITY_ID NUMBER NOT NULL,
    SOURCE_TEXT VARCHAR2(1000),
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE RAG_DOCUMENT_ENTITY_LINKS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
