-- Trace-derived agent memory table for Oracle.
-- No existing tables are dropped.
-- CREATED_AT is used consistently; CREATE_TIME is intentionally not used.

CREATE TABLE RAG_AGENT_MEMORIES (
    ID NUMBER PRIMARY KEY,
    MEMORY_TYPE VARCHAR2(50) NOT NULL,
    MEMORY_KEY VARCHAR2(255) NOT NULL,
    MEMORY_VALUE CLOB,
    INTENT VARCHAR2(100),
    ENTITY_NAME VARCHAR2(255),
    FAILURE_TYPE VARCHAR2(100),
    SOURCE_TYPE VARCHAR2(50),
    SOURCE_ID VARCHAR2(100),
    CONFIDENCE NUMBER(10, 4),
    USAGE_COUNT NUMBER DEFAULT 1 NOT NULL,
    LAST_USED_AT DATE,
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE RAG_AGENT_MEMORIES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE INDEX IDX_RAG_AGENT_MEM_TYPE_KEY
    ON RAG_AGENT_MEMORIES (MEMORY_TYPE, MEMORY_KEY);

CREATE INDEX IDX_RAG_AGENT_MEM_ENTITY
    ON RAG_AGENT_MEMORIES (ENTITY_NAME);

CREATE INDEX IDX_RAG_AGENT_MEM_FAILURE
    ON RAG_AGENT_MEMORIES (FAILURE_TYPE);

CREATE INDEX IDX_RAG_AGENT_MEM_UPDATED
    ON RAG_AGENT_MEMORIES (UPDATED_AT);
