-- Day 5 lightweight relation layer
-- Execute this script manually before the first Day 5 relation build/query run.
-- This script only adds new relation table objects and does not remove existing tables.

CREATE TABLE RAG_ENTITY_RELATIONS (
    ID NUMBER PRIMARY KEY,
    SOURCE_ENTITY_ID NUMBER NOT NULL,
    TARGET_ENTITY_ID NUMBER NOT NULL,
    RELATION_TYPE VARCHAR2(50) NOT NULL,
    DOCUMENT_ID NUMBER,
    CHUNK_ID NUMBER,
    EVIDENCE_TEXT VARCHAR2(1000),
    CREATED_AT DATE DEFAULT SYSDATE
);

ALTER TABLE RAG_ENTITY_RELATIONS
    ADD CONSTRAINT UK_RAG_ENTITY_RELATIONS_UNQ
    UNIQUE (SOURCE_ENTITY_ID, TARGET_ENTITY_ID, RELATION_TYPE, DOCUMENT_ID, CHUNK_ID);

CREATE SEQUENCE RAG_ENTITY_RELATIONS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE INDEX IDX_RAG_ENTITY_REL_SRC
    ON RAG_ENTITY_RELATIONS (SOURCE_ENTITY_ID);

CREATE INDEX IDX_RAG_ENTITY_REL_TGT
    ON RAG_ENTITY_RELATIONS (TARGET_ENTITY_ID);

CREATE INDEX IDX_RAG_ENTITY_REL_TYPE
    ON RAG_ENTITY_RELATIONS (RELATION_TYPE);

CREATE INDEX IDX_RAG_ENTITY_REL_DOC
    ON RAG_ENTITY_RELATIONS (DOCUMENT_ID);

CREATE INDEX IDX_RAG_ENTITY_REL_CHUNK
    ON RAG_ENTITY_RELATIONS (CHUNK_ID);
